import unittest
from pathlib import Path


class WebUITests(unittest.TestCase):
    def test_index_references_core_api_endpoints_and_controls(self) -> None:
        html = Path("web/index.html").read_text(encoding="utf-8")

        self.assertIn("/health", html)
        self.assertIn('api("GET", "/campaigns")', html)
        self.assertIn('api("GET", "/coc")', html)
        self.assertIn('api("DELETE", "/campaigns/" + campaignId)', html)
        self.assertIn("/campaigns/import", html)
        self.assertIn("/campaigns/demo-with-character", html)
        self.assertIn("/coc/import", html)
        self.assertIn("/coc/generate", html)
        self.assertIn("/coc/demo", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/summary", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/review", html)
        self.assertIn("/keeper-suggestion", html)
        self.assertIn("/sample-character", html)
        self.assertIn("/summary", html)
        self.assertIn("/log?limit=50", html)
        self.assertIn("returned_count", html)
        self.assertIn("event_count", html)
        self.assertIn("filtered_count", html)
        self.assertIn("logStatus", html)
        self.assertIn("composeCampaignStatus", html)
        self.assertIn("composeLogStatus", html)
        self.assertIn('id="logVisibility"', html)
        self.assertIn("reloadCampaignLog", html)
        self.assertIn("encodeURIComponent(logVisibility.value)", html)
        self.assertIn("/actions", html)
        self.assertIn("/dm-suggestion", html)
        self.assertIn("/rules/search", html)
        self.assertIn('id="adventureFile"', html)
        self.assertIn('id="demoButton"', html)
        self.assertIn('id="campaignsButton"', html)
        self.assertIn('id="campaignList"', html)
        self.assertIn('id="cocFile"', html)
        self.assertIn('id="cocPremise"', html)
        self.assertIn('id="cocGenerateButton"', html)
        self.assertIn('id="cocImportButton"', html)
        self.assertIn('id="cocDemoButton"', html)
        self.assertIn('id="cocList"', html)
        self.assertIn('id="rulesQuery"', html)
        self.assertIn('id="rulesResults"', html)
        self.assertIn('id="clearTranscriptButton"', html)
        self.assertIn('id="actionInput"', html)
        self.assertIn('id="dmButton"', html)
        self.assertIn('id="runSuggestedButton"', html)
        self.assertIn("renderCampaignList", html)
        self.assertIn("importCocScenario", html)
        self.assertIn("generateCocScenario", html)
        self.assertIn("require_review_ok", html)
        self.assertIn("loadCocDemo", html)
        self.assertIn("loadCocScenario", html)
        self.assertIn("refreshCocView", html)
        self.assertIn("renderCocSummary", html)
        self.assertIn("renderInvestigator", html)
        self.assertIn("renderCocEvidence", html)
        self.assertIn("renderCocReviewFindings", html)
        self.assertIn("composeCocStatus", html)
        self.assertIn("refreshCampaignView", html)
        self.assertIn("refreshCampaignLog", html)
        self.assertIn("renderRecentEvents", html)
        self.assertIn("recent_events", html)
        self.assertIn("transcriptEventIds", html)
        self.assertIn("appendTranscriptMessage", html)
        self.assertIn("actorClass", html)
        self.assertIn("eventMeta", html)
        self.assertIn("message-meta", html)
        self.assertIn("created_at", html)
        self.assertIn("visibility", html)
        self.assertIn("clearTranscriptView", html)
        self.assertIn(".message", html)
        self.assertIn("renderRulesResults", html)
        self.assertIn("data-use-rule", html)
        self.assertIn("useRuleResult", html)
        self.assertIn("Loaded rule query into the action box.", html)
        self.assertIn("ruleSourceSummary", html)
        self.assertIn("dmSuggestionMetadata", html)
        self.assertIn("Action: ", html)
        self.assertIn("searchRules", html)
        self.assertIn("suggestTypedAction", html)
        self.assertIn("suggestCocAction", html)
        self.assertIn("runSuggestedAction", html)
        self.assertIn("pendingSuggestedAction", html)
        self.assertIn("lastRulesQuery", html)
        self.assertIn("actionInput.value = action", html)
        self.assertIn("updateSuggestedActionControl", html)
        self.assertIn("apiErrorFromResponse", html)
        self.assertIn("setupHint", html)
        self.assertIn("ai_provider_not_configured", html)
        self.assertIn("ai_provider_error", html)
        self.assertIn("AI Keeper", html)
        self.assertIn("rules_corpus_not_configured", html)
        self.assertIn("featureLabel", html)
        self.assertIn("persistent_state", html)
        self.assertIn("coc_scenario_count", html)
        self.assertIn("cocScenarios", html)
        self.assertIn("scenarioId", html)
        self.assertIn("system_id", html)
        self.assertIn("summary.completed", html)
        self.assertIn("scenario.completed", html)
        self.assertIn("summary.inventory", html)
        self.assertIn("summary.exits", html)
        self.assertIn("exit.available", html)
        self.assertIn("Blocked Exits", html)
        self.assertIn("completion_progress", html)
        self.assertIn("completionProgressLabel", html)
        self.assertIn("Ending", html)
        self.assertIn("inventory_count", html)
        self.assertIn("summary.npcs", html)
        self.assertIn("npc.name", html)
        self.assertIn("cocReview", html)
        self.assertIn("review.findings", html)
        self.assertIn("checkHealth();", html)
        self.assertIn("session_event_count", html)
        self.assertIn("String(value ?? \"\")", html)
        self.assertIn("current_location_id", html)
        self.assertIn("current_location_name", html)
        self.assertIn("available_actions", html)
        self.assertIn("renderQuickActions", html)
        self.assertIn("monster_action_strategy", html)
        self.assertIn("last_automatic_action", html)
        self.assertIn("morale_hint", html)
        self.assertIn("Monster AI", html)
        self.assertIn("Morale", html)
        self.assertIn("spellcasting.slots", html)
        self.assertIn("concentration_spell_name", html)
        self.assertIn("Concentration ", html)
        self.assertIn("Conditions ", html)
        self.assertIn("character.conditions", html)
        self.assertIn("death_saves", html)
        self.assertIn("Death saves ", html)
        self.assertIn("location.exits", html)
        self.assertIn("Exit count", html)
        self.assertIn("NPC count", html)
        self.assertIn("combatant_count", html)
        self.assertIn("active_combat", html)
        self.assertIn("Combat ", html)
        self.assertIn("defeated", html)
        self.assertIn("current_resources", html)
        self.assertIn("targetable_enemies", html)
        self.assertIn("targetable_allies", html)
        self.assertIn("Targets", html)
        self.assertIn("Target Actions", html)
        self.assertIn("combatTargetActions", html)
        self.assertIn("normalized.endsWith", html)
        self.assertIn("resourceLabel", html)
        self.assertIn("Movement", html)
        self.assertNotIn("DEMO_ADVENTURE", html)

    def test_index_does_not_depend_on_external_assets(self) -> None:
        html = Path("web/index.html").read_text(encoding="utf-8")

        self.assertNotIn("https://", html)
        self.assertNotIn("http://cdn", html.lower())
        self.assertNotIn("<script src=", html.lower())
        self.assertNotIn("<link rel=\"stylesheet\"", html.lower())


if __name__ == "__main__":
    unittest.main()
