import unittest
from pathlib import Path


class WebUITests(unittest.TestCase):
    def test_index_references_core_api_endpoints_and_controls(self) -> None:
        html = Path("web/index.html").read_text(encoding="utf-8")

        self.assertIn("/health", html)
        self.assertIn('api("GET", "/campaigns")', html)
        self.assertIn('api("GET", "/coc")', html)
        self.assertIn('api("DELETE", "/campaigns/" + campaignId)', html)
        self.assertIn("/campaigns/import", html)
        self.assertIn("/campaigns/demo-with-character", html)
        self.assertIn("/coc/import", html)
        self.assertIn("/coc/generate", html)
        self.assertIn("/coc/demo-options", html)
        self.assertIn("/coc/demo", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/summary", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/review", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/briefing", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/table-packet", html)
        self.assertIn("/coc/\" + state.scenarioId + \"/player-card", html)
        self.assertIn("Player Card", html)
        self.assertIn("playerCardButton", html)
        self.assertIn("renderPlayerCard", html)
        self.assertIn("loadPlayerCard", html)
        self.assertIn("cocPlayerCard", html)
        self.assertIn("Keeper Briefing", html)
        self.assertIn("briefingButton", html)
        self.assertIn("tablePacketButton", html)
        self.assertIn("loadTablePacket", html)
        self.assertIn("renderTablePacket", html)
        self.assertIn("packet-view", html)
        self.assertIn("packet-section", html)
        self.assertIn("packet-actions", html)
        self.assertIn("scenario_profile", html)
        self.assertIn("clue_map", html)
        self.assertIn("npc_cards", html)
        self.assertIn("Scene Beats", html)
        self.assertIn("Clue Map", html)
        self.assertIn("NPC Cards", html)
        self.assertIn("keeperBriefing", html)
        self.assertIn("loadKeeperBriefing", html)
        self.assertIn("renderKeeperBriefing", html)
        self.assertIn("spotlight_actions", html)
        self.assertIn("opening", html)
        self.assertIn("data-keeper-action", html)
        self.assertIn("button.dataset.keeperAction", html)
        self.assertIn("cocBriefing", html)
        self.assertIn("/keeper-suggestion", html)
        self.assertIn("/sample-character", html)
        self.assertIn("/summary", html)
        self.assertIn("/log?limit=50", html)
        self.assertIn("returned_count", html)
        self.assertIn("event_count", html)
        self.assertIn("filtered_count", html)
        self.assertIn("logStatus", html)
        self.assertIn("composeCampaignStatus", html)
        self.assertIn("composeLogStatus", html)
        self.assertIn('id="logVisibility"', html)
        self.assertIn("reloadCampaignLog", html)
        self.assertIn("encodeURIComponent(logVisibility.value)", html)
        self.assertIn("/actions", html)
        self.assertIn("/dm-suggestion", html)
        self.assertIn("/rules/search", html)
        self.assertIn('id="adventureFile"', html)
        self.assertIn('id="demoButton"', html)
        self.assertIn('id="campaignsButton"', html)
        self.assertIn('id="campaignList"', html)
        self.assertIn('id="cocFile"', html)
        self.assertIn('id="cocPremise"', html)
        self.assertIn('id="cocGenerateButton"', html)
        self.assertIn('id="cocImportButton"', html)
        self.assertIn('id="cocDemoButton"', html)
        self.assertIn('id="cocDemoScenario"', html)
        self.assertIn('value="glass_lake"', html)
        self.assertIn('id="cocList"', html)
        self.assertIn('id="rulesQuery"', html)
        self.assertIn('id="rulesResults"', html)
        self.assertIn('id="clearTranscriptButton"', html)
        self.assertIn('id="actionInput"', html)
        self.assertIn('id="dmButton"', html)
        self.assertIn('id="runSuggestedButton"', html)
        self.assertIn("renderCampaignList", html)
        self.assertIn("importCocScenario", html)
        self.assertIn("generateCocScenario", html)
        self.assertIn("require_review_ok", html)
        self.assertIn("loadCocDemo", html)
        self.assertIn("loadCocDemoOptions", html)
        self.assertIn("renderCocDemoOptions", html)
        self.assertIn("cocDemoOptions", html)
        self.assertIn('{ scenario: cocDemoScenario.value }', html)
        self.assertIn("loadCocScenario", html)
        self.assertIn("refreshCocView", html)
        self.assertIn("renderCocSummary", html)
        self.assertIn('id="activityTitle"', html)
        self.assertIn('activityTitle.textContent = "Investigation"', html)
        self.assertIn('activityTitle.textContent = "Combat"', html)
        self.assertIn("renderCocInvestigationPanel", html)
        self.assertIn("renderCocSanityState", html)
        self.assertIn("Sanity State", html)
        self.assertIn("No active SAN conditions", html)
        self.assertIn("summary.investigator", html)
        self.assertIn("renderCocProgress", html)
        self.assertIn("renderCocExits", html)
        self.assertIn("renderCocNpcs", html)
        self.assertIn("renderCocDiscoveredClues", html)
        self.assertIn("Ending Progress", html)
        self.assertIn("Discovered Clues", html)
        self.assertIn("Required clues", html)
        self.assertIn("renderInvestigator", html)
        self.assertIn("current_mp", html)
        self.assertIn("max_mp", html)
        self.assertIn("renderCocEvidence", html)
        self.assertIn("renderCocPartialClues", html)
        self.assertIn("partialLeadMeta", html)
        self.assertIn("Luck cost", html)
        self.assertIn("renderCocReviewFindings", html)
        self.assertIn("composeCocStatus", html)
        self.assertIn("refreshCampaignView", html)
        self.assertIn("refreshCampaignLog", html)
        self.assertIn("renderRecentEvents", html)
        self.assertIn("renderCocRecentEvents", html)
        self.assertIn("appendTranscriptLine", html)
        self.assertIn('"coc:" + line', html)
        self.assertIn("state.cocSummary.recent_events", html)
        self.assertIn("recent_events", html)
        self.assertIn("transcriptEventIds", html)
        self.assertIn("appendTranscriptMessage", html)
        self.assertIn("actorClass", html)
        self.assertIn("eventMeta", html)
        self.assertIn("message-meta", html)
        self.assertIn("created_at", html)
        self.assertIn("visibility", html)
        self.assertIn("clearTranscriptView", html)
        self.assertIn(".message", html)
        self.assertIn("renderRulesResults", html)
        self.assertIn("data-use-rule", html)
        self.assertIn("useRuleResult", html)
        self.assertIn("Loaded rule query into the action box.", html)
        self.assertIn("ruleSourceSummary", html)
        self.assertIn("dmSuggestionMetadata", html)
        self.assertIn("Action: ", html)
        self.assertIn("searchRules", html)
        self.assertIn("suggestTypedAction", html)
        self.assertIn("suggestCocAction", html)
        self.assertIn("runSuggestedAction", html)
        self.assertIn("pendingSuggestedAction", html)
        self.assertIn("lastRulesQuery", html)
        self.assertIn("actionInput.value = action", html)
        self.assertIn("action.includes(\"<text>\")", html)
        self.assertIn("Complete the action text, then send.", html)
        self.assertIn("action.replace(\"<text>\", \"\")", html)
        self.assertIn("updateSuggestedActionControl", html)
        self.assertIn("apiErrorFromResponse", html)
        self.assertIn("setupHint", html)
        self.assertIn("ai_provider_not_configured", html)
        self.assertIn("ai_provider_error", html)
        self.assertIn("AI Keeper", html)
        self.assertIn("rules_corpus_not_configured", html)
        self.assertIn("featureLabel", html)
        self.assertIn("persistent_state", html)
        self.assertIn("coc_scenario_count", html)
        self.assertIn("cocScenarios", html)
        self.assertIn("scenarioId", html)
        self.assertIn("system_id", html)
        self.assertIn("summary.completed", html)
        self.assertIn("scenario.completed", html)
        self.assertIn("completion_required_count", html)
        self.assertIn("completion_remaining_count", html)
        self.assertIn("completionCountLabel", html)
        self.assertIn("summary.inventory", html)
        self.assertIn("summary.exits", html)
        self.assertIn("exit.available", html)
        self.assertIn("Blocked Exits", html)
        self.assertIn("completion_progress", html)
        self.assertIn("completionProgressLabel", html)
        self.assertIn("Ending", html)
        self.assertIn("keeper_hint", html)
        self.assertIn("Keeper Hint", html)
        self.assertIn("partial_clue_count", html)
        self.assertIn("Partial Leads", html)
        self.assertIn("inventory_count", html)
        self.assertIn("summary.npcs", html)
        self.assertIn("npc.name", html)
        self.assertIn("cocReview", html)
        self.assertIn("review.findings", html)
        self.assertIn("checkHealth();", html)
        self.assertIn("session_event_count", html)
        self.assertIn("scenario.session_event_count", html)
        self.assertIn("Events ", html)
        self.assertIn("String(value ?? \"\")", html)
        self.assertIn("current_location_id", html)
        self.assertIn("current_location_name", html)
        self.assertIn("available_actions", html)
        self.assertIn("renderQuickActions", html)
        self.assertIn("groupQuickActions", html)
        self.assertIn("quickActionGroupLabel", html)
        self.assertIn("quick-action-group", html)
        self.assertIn("quick-action-buttons", html)
        self.assertIn("Skills", html)
        self.assertIn("action === \"skills\"", html)
        self.assertIn("Health", html)
        self.assertIn("take damage", html)
        self.assertIn("recover luck", html)
        self.assertIn("spend luck", html)
        self.assertIn("heal ", html)
        self.assertIn("Notes", html)
        self.assertIn("Investigation", html)
        self.assertIn("monster_action_strategy", html)
        self.assertIn("last_automatic_action", html)
        self.assertIn("morale_hint", html)
        self.assertIn("Monster AI", html)
        self.assertIn("Morale", html)
        self.assertIn("spellcasting.slots", html)
        self.assertIn("concentration_spell_name", html)
        self.assertIn("Concentration ", html)
        self.assertIn("Conditions ", html)
        self.assertIn("character.conditions", html)
        self.assertIn("death_saves", html)
        self.assertIn("Death saves ", html)
        self.assertIn("location.exits", html)
        self.assertIn("Exit count", html)
        self.assertIn("NPC count", html)
        self.assertIn("combatant_count", html)
        self.assertIn("active_combat", html)
        self.assertIn("Combat ", html)
        self.assertIn("defeated", html)
        self.assertIn("current_resources", html)
        self.assertIn("targetable_enemies", html)
        self.assertIn("targetable_allies", html)
        self.assertIn("Targets", html)
        self.assertIn("Target Actions", html)
        self.assertIn("combatTargetActions", html)
        self.assertIn("normalized.endsWith", html)
        self.assertIn("resourceLabel", html)
        self.assertIn("Movement", html)
        self.assertNotIn("DEMO_ADVENTURE", html)

    def test_index_does_not_depend_on_external_assets(self) -> None:
        html = Path("web/index.html").read_text(encoding="utf-8")

        self.assertNotIn("https://", html)
        self.assertNotIn("http://cdn", html.lower())
        self.assertNotIn("<script src=", html.lower())
        self.assertNotIn("<link rel=\"stylesheet\"", html.lower())


if __name__ == "__main__":
    unittest.main()
